export const slideInRightAnimation = `/* ----------------------------------------------
* Generated by Animista on 2023-9-21 22:17:46
* Licensed under FreeBSD License.
* See http://animista.net/license for more info. 
* w: http://animista.net, t: @cssanimista
* ---------------------------------------------- */

/**
* ----------------------------------------
* animation slide-right
* ----------------------------------------
*/
@-webkit-keyframes slide-right {
 0% {
   -webkit-transform: translateX(100px);
           transform: translateX(100px);
 }
 100% {
   -webkit-transform: translateX(0px);
           transform: translateX(0px);
 }
}
@keyframes slide-right {
 0% {
   -webkit-transform: translateX(100px);
           transform: translateX(100px);
 }
 100% {
   -webkit-transform: translateX(0px);
           transform: translateX(0px);
 }
}
`;
